jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: ./.github/actions/prepare
      - run: pnpm format --list-different

name: Prettier

on:
  pull_request: ~
  push:
    branches:
      - main
